### ISSUE TITLE
Rolling Updates section needs a exampe-auth:2.0.0 tag

### ISSUE THREAD

**Issue by dylangrafmyre** [udacity/ud615#1]
In the deploying Microservices section of the class under Rolling Updates. Kelsey does a rolling update by editing `demployments/auth.yml`. In the video he changes the image to `kelseyhightower/auth:2.0.0`.

Following along using this cloned app `deployments/auth.yml` has `udacity/example-auth:1.0.0`. 
https://github.com/udacity/ud615/blob/master/kubernetes/deployments/auth.yaml#L15

However you do not have a tagged version `udacity/example-auth:2.0.0` in your Docker Hub repo. This will cause the rolling update to fail. 
https://hub.docker.com/r/udacity/example-auth/tags/

I need to use Kelsey's `auth:2.0.0` image to complete the process.

Enjoyed the class. Thanks!

**Comment by knpwrs** [comment]
Three months later and this is still an issue.

**Comment by lcrisci** [comment]
Can we get someone to fix this simple issue? :)

We managed to figure out what was going on but it might not be so evident for newcomers ( although it's a good troubleshooting opportunity! )

**Comment by estevejm** [comment]
I also had to use Kelsey's image to continue, please add the `2.0.0` tag as [https://hub.docker.com/r/kelseyhightower/auth/tags/](https://hub.docker.com/r/kelseyhightower/auth/tags/)

**Comment by XiaoJu** [comment]
issue still open as per today november 9th, 2016.

**Comment by au9ustine** [comment]
Confirmed this issue still exists on Nov 24, 2016

**Comment by XiaoJu** [comment]
Bug reports should be posted on the udacity forum:
https://discussions.udacity.com/t/course-related-bugs/170401

**Comment by eosrei** [comment]
Not to step on any toes, but I can fix this so... I did. https://hub.docker.com/r/udacity/example-auth/tags/
