### ISSUE TITLE
error: unable to recognize "deployments/auth.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by PierreFritsch** [udacity/ud615#10]
When I use `kubectl` version v1.17.2 to [create the *auth* deployment](https://classroom.udacity.com/courses/ud615/lessons/7826932295/concepts/81891227730923):

    kubectl create -f deployments/auth.yaml

Then I get the error:

    error: unable to recognize "deployments/auth.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by sanskar2999** [comment]
One of the workarounds I found was: 
1. changing the apiversion of all the deployments file that were in use to apps/v1
2.
In the yaml file add the selector field this way:
spec:
  selector:
    matchLabels:
      app: (name of the app, can match with container name eg: auth, hello etc for the given

this will work
