### ISSUE TITLE
This example is not working anymore

### ISSUE THREAD

**Issue by Rukeith** [udacity/ud615#6]
This example is too old, it cant' work.

**Comment by lukmdo** [comment]
@Rukeith your comment does not have enough context. 
Please share what you found not working or maybe close this issue.

**Comment by abdennour** [comment]
Do not close the issue. The example does not work & The errors are as following : 

### 1. When running `go build -o ./bin/monolith ./monolith` inside `~/gopath:/google/gopath/src/github.com/udacity/ud615/app`

```
monolith/main.go:12:2: cannot find package "github.com/braintree/manners" in any of:
        /usr/local/go/src/github.com/braintree/manners (from $GOROOT)
        /home/abdennour_toumi/gopath/src/github.com/braintree/manners (from $GOPATH)
        /google/gopath/src/github.com/braintree/manners
monolith/main.go:13:2: cannot find package "github.com/udacity/ud615/app/handlers" in any of:
        /usr/local/go/src/github.com/udacity/ud615/app/handlers (from $GOROOT)
        /home/abdennour_toumi/gopath/src/github.com/udacity/ud615/app/handlers (from $GOPATH)
        /google/gopath/src/github.com/udacity/ud615/app/handlers
monolith/main.go:14:2: cannot find package "github.com/udacity/ud615/app/health" in any of:
        /usr/local/go/src/github.com/udacity/ud615/app/health (from $GOROOT)
        /home/abdennour_toumi/gopath/src/github.com/udacity/ud615/app/health (from $GOPATH)
        /google/gopath/src/github.com/udacity/ud615/app/health
monolith/main.go:15:2: cannot find package "github.com/udacity/ud615/app/user" in any of:
        /usr/local/go/src/github.com/udacity/ud615/app/user (from $GOROOT)
        /home/abdennour_toumi/gopath/src/github.com/udacity/ud615/app/user (from $GOPATH)
        /google/gopath/src/github.com/udacity/ud615/app/user
```

### 2. When trying to install dependencies using `go get -u` , we got as stderr  : 

```
package _/home/abdennour_toumi/gopath_/google/gopath/src/github.com/udacity/ud615/app: unrecognized import path "_/home/abdennour_toumi/gopath_/google/gopath/src/github.com/udacity/ud615/app" (import path does not begin with hostname)
```

**Comment by facundomedica** [comment]
I made it work by manually installing all deps with `go get`

**Comment by matthewbrahms** [comment]
Used the package names found in the error output to get the dependencies manually one-by-one:
`go get github.com/.../...`

For example:
`go get github.com/braintree/manners`

**Comment by eosrei** [comment]
Make sure your Go installation is configured correctly. I recommend the newest Go. [The dependencies are vendored on this project](https://github.com/udacity/ud615/tree/master/app/vendor/), `go get` isn't needed. Example run within Docker from a direct clone:
```
$ docker run -it --rm -v $PWD:/go/src/github.com/udacity/ud615/app golang:1.9-alpine sh
/go # cd /go/src/github.com/udacity/ud615/app
/go/src/github.com/udacity/ud615/app # go build -o ./bin/monolith ./monolith
/go/src/github.com/udacity/ud615/app # ./bin/monolith 
2017/12/27 23:38:10 Starting server...
2017/12/27 23:38:10 Health service listening on 0.0.0.0:81
2017/12/27 23:38:10 HTTP service listening on 0.0.0.0:80
^C2017/12/27 23:38:11 Captured interrupt. Exiting...
```

**Comment by thirdender** [comment]
Following the directions in the README seems to work. I did that after attempting `go get` (which seemed to fail), so I'm not sure exactly what fixed my issues.

**Comment by nayanajith** [comment]
I had the same error as I put **go** in the **$GOPATH**. Moving **go** to **/opt/go** solved the issue.

**Comment by evanjmg** [comment]
There are two big issues with this project and they are a result of setup instructions: 
1. First thing need to do is to install the outside dependencies - in this case 
 run `go get github.com/braintree/manners`
2. Make sure your  project is inside your current GOPATH directory. If you install go before, you'll need to git clone the project inside where your project is. In my case I had to copy like this: `cp -r github.com /usr/local/Cellar/go/1.11.2/src/`

**Comment by fuaadahmad** [comment]
I was getting all sort of errors because I had opened up the terminal before executing following command from lecture 5
echo "export GOPATH=~/go" >> ~/.bashrc

**Comment by jbsledzik** [comment]
Setting `GOPATH` var to `~/.go` and placing project files in there (properly nested) according to instructions on Udacity tutorial makes build command works.
